### ISSUE TITLE
Plan to support Wagtail 3.0 to be released in May 2022

### ISSUE THREAD

**Issue by danhayden** [neon-jungle/wagtail-birdsong#19]
Regarding [Upcoming breaking changes affecting Wagtail community projects](https://gist.github.com/thibaudcolas/828ad05f95063e9cf4cb621daff50dcb) 

I have wagtail-birdsong working on a project I am currently developing on Wagtail 3.0rc2; mostly based on the changes in https://github.com/neon-jungle/wagtail-birdsong/pull/15 plus running `wagtail updatemodulepaths` as outlined in https://docs.wagtail.org/en/latest/releases/3.0.html#upgrade-considerations-changes-affecting-all-projects.

Are there any other considerations or blocks preventing the implementation of these changes? I'm asking as https://github.com/neon-jungle/wagtail-birdsong/pull/15 is yet to be reviewed and didn't want to submit a further PR before this has been done as Wagtail 3.0 compatibility will be built on top of the changes for Wagtail 2.15 compatibility. Also as these changes would break compatibility with Wagtail versions less than 3.0 the release would likely require a major version bump which comes with it's own considerations.

I'm happy to help if I can :smiley:

**Comment by seb-b** [comment]
Thanks for picking these up, please don't hesitate to open more merge requests. The only blocker at the moment is our ability to verify things manually before cutting a release, we're a bit over capacity at the moment and some of our wagtail packages have been a bit neglected. 

I'll be able to have a look at #15 hopefully soon (it looks fine from a cursory glance), but the sooner you open a 3.0 compatibly merge request the better, and it can be merged once 3.0 comes out

**Comment by danhayden** [comment]
Just pushed an update to https://github.com/neon-jungle/wagtail-birdsong/pull/15 (added missing migrations, fixed formatting inconsistency and fixed a typo I had introduced in the data-action of create_campaign.html)

When I get a chance I will work on the 3.0 compatibility in a new PR based on the code in https://github.com/neon-jungle/wagtail-birdsong/pull/15

**Comment by danhayden** [comment]
Have just done a quick check with https://github.com/neon-jungle/wagtail-birdsong/pull/15 on a new test project on wagtail==3.0rc2 to see what would need doing.

On the test project I installed wagtail-birdsong (using https://github.com/neon-jungle/wagtail-birdsong/pull/15), followed the  setup instructions from the readme then ran `wagtail updatemodulepaths` followed by `python manage.py migrate` and all seems to be working. 

I believe this is due to there being fallback imports still in wagtail 3.0 as mentioned by Matt Westcott on the wagtail slack channel => https://wagtailcms.slack.com/archives/C0K2WLTRS/p1650904500353459?thread_ts=1650638782.025949&cid=C0K2WLTRS

![list-view](https://user-images.githubusercontent.com/1385253/165753725-b74bca3b-6da6-4cfa-ab58-18b6524cd60d.png)


There is a minor padding issue in the header on the edit campaign view as can be seen below, but all else appears fine.
![edit-view](https://user-images.githubusercontent.com/1385253/165753753-d2b87db9-4d4b-4ef2-b151-6bf8517fd5f5.png)

**Comment by danhayden** [comment]
Wagtail 3.0rc3 has now been released but appears to have introduced a few style regressions that affect wagtail-birdsong; I have provided feedback on the Wagtail 3.0 release candidates discussion page => https://github.com/wagtail/wagtail/discussions/8362#discussioncomment-2661898

**Comment by seb-b** [comment]
https://github.com/neon-jungle/wagtailvideos/issues/91 - this might be of use for anyone tackling this
