### ISSUE TITLE
Wagtail 5 breaks project

### ISSUE THREAD

**Issue by daveclarkit** [neon-jungle/wagtail-birdsong#41]
under wagtail 5 the project will not load as its using removed / changed namespace references - I tested changing the namespaces and the code runs - but the custom menu registration functions don't work under wagtail 5 (or 4.2)

**Comment by GorgonSlayer** [comment]
Anyone working on this? I'm happy to attempt a fix if not.

**Comment by seb-b** [comment]
> Anyone working on this? I'm happy to attempt a fix if not.

Not currently no, feel free to take it on. 
I also don't mind doing a new release with a minimum version of 5.0+ is backwards compatibility is too much of a problem. People can always install older version of birdsong for older versions of wagtail

**Comment by ramiboutas** [comment]
I opened a pull request on this regard.

https://github.com/neon-jungle/wagtail-birdsong/pull/42
