### ISSUE TITLE
Using Django's mail utilities to support multiple backend

### ISSUE THREAD

**Issue by fzerman** [neon-jungle/wagtail-birdsong#52]
You should use Django's mail utilities to support multiple backend instead of write your own. Because other django mail provider packages like django-anymail override this utilities. Then u can use the provider without changing your code. You should consider https://docs.djangoproject.com/en/5.0/topics/email/#send-mass-mail.

**Comment by seb-b** [comment]
the built in smtp backend does use the standard django methods for [sending mail](https://github.com/neon-jungle/wagtail-birdsong/blob/master/birdsong/backends/smtp.py#L73), if you dive into that class you'll see the `send_mass_html_mail` uses the mail utilities. 
Are you having a specific problem running django-anymail and birdsong alongside each other?

**Comment by fzerman** [comment]
No, i dont have. when i see, "multiple provider will add" in readme, i think you will point other services like mailgun, mailchimp, etc. So, i added this issue for an small advice.
