### ISSUE TITLE
Admin Interface

### ISSUE THREAD

**Issue by glanzel** [neon-jungle/wagtail-birdsong#6]
I think i missed somethiing in the dokumentation, but i don't even understand where to find the interface to write the emails in the wagtail admin interface.

**Comment by seb-b** [comment]
Did you register your admin using the `@modeladmin_register` decorator?

There's an example in the test app you can see here: https://github.com/neon-jungle/wagtail-birdsong/blob/master/tests/app/wagtail_hooks.py

**Comment by glanzel** [comment]
Thanks very much for your reply.
Even though my question was very inaccurate.
With the help of the test app I managed it to see the the admin entry.
That was a very good hint.
I am still not sure what exactly the main problem was. At one point i got the folder structure wrong. 
(but for me it seems ther was a second "caching" problem which might got something to do with the fact that i use apache / passenger as a server on my local machine but i cant reproduce the problem)

offtopic: anyhow it now seems to me that mjml won't work if its only installed in the virtual env. (it said "cant execute mjml -i -s" before i installed it systemwide) that could be a dealbreaker for me cause i want to deploy the webapplikation on a hosted server where i cant install systemwide

**Comment by seb-b** [comment]
You could try creating a tcp/http service for mjml? There's instructions in the django-mjml readme: https://github.com/liminspace/django-mjml#advanced-settings

**Comment by glanzel** [comment]
Yes you are totally right. Thank you very much. I use
```
`MJML_BACKEND_MODE = 'httpserver'
MJML_HTTPSERVERS = [
    {
        'URL': 'https://api.mjml.io/v1/render',  # official MJML API
        'HTTP_AUTH': ('<Application ID>', '<Secret Key>'),
    },
 ]`
```

now and it works like a charm.
I am happy :-)

( I had a delay in reading the Email configuration from settings file in the beginning again, maybe there is still a little missconfiguration on my side, so if someone knows why something like this could happen... )
